//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class devvn_xaphuongthitran
    {
        public string xaid { get; set; }
        public string nameXa { get; set; }
        public string typeXa { get; set; }
        public string maqh { get; set; }
    }
}
