//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public string id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string scale { get; set; }
        public string area { get; set; }
        public string legal { get; set; }
        public string planning { get; set; }
        public string handoverTime { get; set; }
        public string salePrice { get; set; }
        public string introduce { get; set; }
        public string overview { get; set; }
        public string overviewImage { get; set; }
        public string location { get; set; }
        public string locationImage { get; set; }
        public string masterPlan { get; set; }
        public string masterPlanImage { get; set; }
        public string utilities { get; set; }
        public string utilitiesImage { get; set; }
        public string investor { get; set; }
    }
}
