//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class RealEstateInfo
    {
        public int id { get; set; }
        public string title { get; set; }
        public string typeRealEstate { get; set; }
        public string img { get; set; }
        public string descriptRealEstate { get; set; }
        public string price { get; set; }
        public string locationRealEstate { get; set; }
        public Nullable<int> area { get; set; }
        public System.DateTime timepost { get; set; }
        public string addressRealEstate { get; set; }
        public Nullable<int> streetWidth { get; set; }
        public string orientation { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> lenght { get; set; }
        public Nullable<int> floors { get; set; }
        public Nullable<int> bedrooms { get; set; }
        public Nullable<int> toilets { get; set; }
        public string furniture { get; set; }
        public string legalDocument { get; set; }
        public Nullable<int> projectId { get; set; }

        // thêm source thẳng vào database / dấu bình phương
        public ImageSource imageSource { get; set; }
        public string squareRoot { get; set; }
    }
}
